name: Build and Push Docker Image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Get version
        id: vars
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "version=v$(date +'%Y.%m.%d-%H%M%S')" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      
      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/project:latest .
          docker tag ${{ secrets.DOCKER_USERNAME }}/project:latest ${{ secrets.DOCKER_USERNAME }}/project:${{ steps.vars.outputs.version }}
          docker push ${{ secrets.DOCKER_USERNAME }}/project:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/project:${{ steps.vars.outputs.version }}
          